### ISSUE TITLE
Simplify number conversions

### ISSUE THREAD

**Issue by alcueca** [HQ20/Fixidity#7]
I did a number of changes in [dev](https://github.com/HQ20/Fixidity/tree/dev).

1. Included the `SafeCast` functions in FixidityLib.
2. Fixed lint and removed unnecessary comments.
3. **Important**: I created a host of new conversion functions that use `SafeCast` internally, to simplify using Fixidity quite a lot. When converting to and from wei now you should be able to use `fixedFromUint(wei, token.decimals())` and `uintFromFixed(fixed, token.decimals())`. No more casting on `ERC20DividendableEth`!

I don't know how to run the tests in this thing anymore, so that I didn't do :man_shrugging:.

Please test. Please consider also migrating Fixidity to a starter-kit configuration.

**Comment by alcueca** [comment]
Hold on, I'll rename all those conversion functions to `toFixed`, `toUint` and `toInt`, so that we follow the javascript naming.

**Comment by alcueca** [comment]
Renamed the functions, applied the PRs from CementDAO, and fixed one bug. Now we need to get the tests to run again. @obernardovieira?

**Comment by uivlis** [comment]
@albertocuestacanada All tests pass, perhaps @obernardovieira could publish again?

**Comment by alcueca** [comment]
I think so, maybe as version 0.1.

**Comment by vibern0** [comment]
Thanks, guys. Yes, Travis is running CI as usual, with tests, and now linting as well. I'll add the coverage reports.

I've released another alpha version (just saw these messages now). Not sure if we should release a stable version, or leave that to cementdao. But in any case, this needs some improvements before a stable release.

**Comment by alcueca** [comment]
Now that I know how things work, I just coded another library that does basically the same as Fixidity in about 50 lines of code. We can leave Fixidity as is.
